name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  workflow_dispatch:

defaults:
  run:
    working-directory: src/TestProject1/ConsoleApp1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

        # .NET 6 ビルド準備
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
          include-prerelease: true

        # Release ビルド
      - name: Build with dotnet
        run: dotnet build --configuration Release

        # テスト1 を実施
      - name: Run test
        run: dotnet test --test-adapter-path ../../TestProject1/TestProject1

        # テスト2 を実施
      - name: Run test
        run: dotnet test --test-adapter-path ../../TestProject2/TestProject2
